### ISSUE TITLE
Lower loading priority of cross-origin iframes

### ISSUE THREAD

**Issue by rschoen** [WICG/interventions#1]
Cross-origin iframes are typically secondary content to the main content of the page. Therefore, it may be beneficial to the user to lower the priority of (or perhaps fully delay?) cross-origin iframes until the main content has loaded. This would decrease network and CPU contention, and ideally dramatically improve the load of the main page.

Since most browsers already have the notion of priority, this could be fairly simple to experiment with.

**Comment by tigt** [comment]
This works excellently for ads, but cramps audio and video embeds, since those are often delegated to platforms like YouTube or Soundcloud. Sometimes those embeds are the entire point of a given post, like Tumblr's Audio and Video post types.

**Comment by hillbrad** [comment]
Please see discussion on https://github.com/WICG/interventions/issues/10   

Cross-origin iframes and postMessage are an important (the best, fastest and safest) cross-origin API channel available to client-side web apps.  Throttle hoggy ads, fine, but please don't break the best API toolkit we have.  :(    

Maybe a 'nice' attribute on iframes, as suggested in #10 ?

**Comment by ojanvafai** [comment]
We didn't have much success here actually making things load better. Some of that is likely due to implementation details. Closing for now. Will reopen if we reconsider or if another browser decides to experiment.
