### ISSUE TITLE
Existing intervention: Font boosting

### ISSUE THREAD

**Issue by cvrebert** [WICG/interventions#11]
By which I mean the behavior that [`text-size-adjust`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-size-adjust) is intended to control (AKA font inflation AKA text autosizing).
The heuristics that browsers use to determine when to apply font boosting and how much to boost the font are not clearly defined (and vary across browsers).
And notably, [there does not currently](http://caniuse.com/#feat=text-size-adjust) appear to be a way to opt out of it in Blink (aside from [ugly hacks](http://stackoverflow.com/a/16432702)).

**Comment by cvrebert** [comment]
> And notably, there does not currently appear to be a way to opt out of it in Blink (aside from ugly hacks).

It seems that this is in the process of being corrected: 😄
https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/-vHFK4g93jA

**Comment by johannhof** [comment]
(As noted in https://github.com/WICG/interventions/pull/72, we intend to archive this repository and are thus triaging and resolving all open issues)

There seems to be some better specification going on in https://github.com/w3c/csswg-drafts/pull/4435, so I would close this issue in favor of that PR. If that doesn't go to the extent you'd like the behavior to be specified (noting that it probably makes sense to leave some space for custom browser behavior), I would recommend commenting or filing a new issue with the CSS WG.
