### ISSUE TITLE
Defer image loads until they are viewable

### ISSUE THREAD

**Issue by KenjiBaheux** [WICG/interventions#15]
Similarly to issue #10, deferring the load of out-of-view images should improve the Loading user experience (more bandwidth & cpu for assets and tasks that are more essential than out-of-view images).

**Comment by johannhof** [comment]
(As noted in https://github.com/WICG/interventions/pull/72, we intend to archive this repository and are thus triaging and resolving all open issues)

As noted in https://github.com/WICG/interventions/issues/10#issuecomment-1108614645, lazy-loading may be something individual browsers want to experiment with and take their results back to a standards forum. However, I don't think the idea needs to be continually tracked at this point.
