### ISSUE TITLE
Ignore clicks on iframes that have moved in the last 200 ms

### ISSUE THREAD

**Issue by alijuma** [WICG/interventions#19]
Unintended clicks on recently-moved elements are a [frustrating but common problem](https://www.youtube.com/watch?v=3tUmh8OfAiY).

To address this, Chrome is considering ignoring clicks on cross-origin iframes when the location of the click would not have been within the bounds of the iframe for all draws that happened within the last 200 ms.

More background can be found [here](https://docs.google.com/document/d/1AL9RMFxLRRTQ818Bi7RPjbxF5JPBhti8XWNbLg83LYE/edit).

**Comment by szager-chromium** [comment]
I would like to revive this proposal, with a few tweaks explained in this updated [doc](https://docs.google.com/document/d/1qzgHiruzTvt0_-rfe7suZRCe2KhSJxiBp28ZTLd9Xls/edit?usp=sharing)

**Comment by johannhof** [comment]
(As noted in https://github.com/WICG/interventions/pull/72, we intend to archive this repository and are thus triaging and resolving all open issues)

Following up in https://github.com/whatwg/html/issues/8012
