### ISSUE TITLE
Allow developers to know when an intervention will/might/did apply

### ISSUE THREAD

**Issue by KenjiBaheux** [WICG/interventions#22]
Developers have expressed the desire to have a way to know if an intervention will/might/did apply.

Sample use cases: 
1. if an ad network knew in advance that doc.written scripts are at risk of an intervention, they would let the auction server know about this extra requirement.
2. if a developer had a way to know that an intervention did trigger, it would allow them to close the feedback loop (e.g. fix code they own, reach out to the owners of the code that yielded an intervention).

**Comment by ojanvafai** [comment]
The reporting side of this is now here: https://github.com/WICG/reporting/blob/master/EXPLAINER.md. The "will apply" side has been done via one-off headers in Chrome for a couple interventions so far. We still want to pursue something there, but I don't think having this placeholder bug open is helpful for that. Will file a new bug if we actually have any proposals.
