### ISSUE TITLE
Start at 30fps and increase to 60fps if the page can handle it

### ISSUE THREAD

**Issue by rschoen** [WICG/interventions#3]
Sometimes 60fps is unreasonable for a given page and device, so perhaps we shouldn't always strive to achieve that. Also, 60fps during page load (with heavy style recalc, layout, JS execution, etc.) is usually unreasonable even for more powerful devices. 

Perhaps we should always load pages at 30fps, and then switch into 60fps once we've detected that it's taking less than 16.6ms of CPU time to generate each frame.

**Comment by johannhof** [comment]
(As noted in https://github.com/WICG/interventions/pull/72, we intend to archive this repository and are thus triaging and resolving all open issues)

This issue didn't get any traction 5 years ago and seems safe to close. I would suggest that this is less of a standards question but rather something that individual browsers should experiment with, so if there's still interest it may make sense to file bugs with browsers.
