### ISSUE TITLE
Existent intervention: Ignore autocomplete=off

### ISSUE THREAD

**Issue by Slayer95** [WICG/interventions#45]
Most browsers disallow turning autocomplete off [in one context or another](http://caniuse.com/#feat=input-autocomplete-onoff),
with the notorious case of Chrome always ignoring it.

**Comment by domenic** [comment]
This is already specified [in the HTML Standard](https://html.spec.whatwg.org/#concept-fe-autofill):

> A user agent may allow the user to override an element's [autofill field name](https://html.spec.whatwg.org/#autofill-field-name), e.g. to change it from "[off](https://html.spec.whatwg.org/#attr-fe-autocomplete-off)" to "[on](https://html.spec.whatwg.org/#attr-fe-autocomplete-on)" to allow values to be remembered and prefilled despite the page author's objections, or to always "[off](https://html.spec.whatwg.org/#attr-fe-autocomplete-off)", never remembering values.
>
> More specifically, user agents may in particular consider replacing the [autofill field name](https://html.spec.whatwg.org/#autofill-field-name) of form c[on](https://html.spec.whatwg.org/#attr-fe-autocomplete-on)trols that match the description given in the first column of the following table, when their autofill field name is either "on" or "[off](https://html.spec.whatwg.org/#attr-fe-autocomplete-off)", with the value given in the second cell of that row.
>
> [... a table showing how to heuristically derive username/password autofill ...]
