### ISSUE TITLE
Pause downloading after a site has loaded too many bytes (#36)

### ISSUE THREAD

**Issue by anirudhcmohan** [WICG/interventions#51]
If a site downloads an excessive number of bytes (above a certain threshold), the site should pause downloading additional bytes until the user has indicated they would like to continue via an opt-in

**Comment by Ajedi32** [comment]
I'm a little curious as to how exactly this would work. I assume this is motivated by a desire to prevent sites from using excessive amounts of data on a metered connection? Would this restriction then only apply there? Or would it also be in effect when connected to unmetered WiFi and the like?

And what counts as "the site" downloading bytes vs "the user"? For example, if a user downloads a large file from a site (like a video or ZIP file), that on its own probably shouldn't trigger the warning, should it?

**Comment by johannhof** [comment]
(As noted in https://github.com/WICG/interventions/pull/72, we intend to archive this repository and are thus triaging and resolving all open issues)

I think it's safe to close this. There hasn't been any significant progress so far and it also doesn't seem like this behavior would need standardization to be supported by browsers.
