### ISSUE TITLE
WebSockets/WebRTC should turn off when scripts do on mobile

### ISSUE THREAD

**Issue by anirudhcmohan** [WICG/interventions#53]
Reduce battery drain by turning off WebSockets / WebRTC when scripts do.

**Comment by johannhof** [comment]
(As noted in https://github.com/WICG/interventions/pull/72, we intend to archive this repository and are thus triaging and resolving all open issues)

It's a bit unclear what is meant here, without scripts how do we have WebSockets/WebRTC? In any case I don't think this has an implementation, so I'll close the issue without a follow-up.
