### ISSUE TITLE
Intervention: Block download from ad iframe

### ISSUE THREAD

**Issue by xyaoinum** [WICG/interventions#67]
We intend to implement in Chrome to block automatic download initiated from ad frames, where "ad frame" is defined by Chrome's [AdTagging](https://cs.chromium.org/chromium/src/docs/ad_tagging.md) infrastructure. See the [design doc](https://docs.google.com/document/d/1fBa8nwvb9g21KTji_kIDHzd7FjCb72pVf33MSb9jSWY).

This intervention can fit in the description "act in a user-agent-defined manner to safeguard the user from a potentially hostile download" in the [HTML Standard](https://html.spec.whatwg.org/multipage/). See also the [pull request](https://github.com/whatwg/html/pull/4450/) that moves around that description a little bit.

**Comment by xyaoinum** [comment]
cc @jkarlin @bslassey @ehsan

**Comment by johannhof** [comment]
(As noted in https://github.com/WICG/interventions/pull/72, we intend to archive this repository and are thus triaging and resolving all open issues)

Closing the issue, as from a standards perspective this seems to have been covered by https://github.com/whatwg/html/pull/4450
