### ISSUE TITLE
Heavy Ad Intervention

### ISSUE THREAD

**Issue by johnivdel** [WICG/interventions#68]
The user agent will unload ads that use an egregious amount of network bandwidth or CPU usage. A small fraction of ads on the web use an egregious amount of system resources. These poorly performant ads (whether intentional or not) harm the user’s browsing experience by making pages slow, draining device battery, and consuming mobile data (for those without unlimited plans).

Full explainer: [https://github.com/johnivdel/heavy-ad-intervention/blob/master/README.md](https://github.com/johnivdel/heavy-ad-intervention/blob/master/README.md)

**Comment by webdevinci** [comment]
@johnivdel I see that this is already running in chrome canary (v. 80), but not in the list of canary release items. 
Can you confirm this will be aligned with Canary's current release date of Feb 4th (or earlier, I didn't check dev?)

**Comment by johannhof** [comment]
(As noted in https://github.com/WICG/interventions/pull/72, we intend to archive this repository and are thus triaging and resolving all open issues)

I think the discussion on this can continue either on https://github.com/whatwg/html/pull/5885 or in the ad-interventions repo, if there's still interest.
